-- Active: 1730294733776@@127.0.0.1@3306
DROP TABLE IF EXISTS users;
CREATE TABLE IF NOT EXISTS `users` (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    firstname VARCHAR(50) NOT NULL,
    lastname VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    confirmed BOOLEAN DEFAULT FALSE
);


DROP TABLE IF EXISTS languages;
CREATE TABLE IF NOT EXISTS `languages` (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    users_id INT NOT NULL, 
    FOREIGN KEY (users_id)REFERENCES users(id)
);